### ISSUE TITLE
Corriger les erreurs et améliorer la page détail selon l'état de données de l'entreprise

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#10]
Lorsque des données sont manquantes pour une entreprise, le code ne devrait pas faire d'erreur, et les composant devraient indiquer un message clair plutôt que s'afficher vide.
Par exemple le code fait une erreur sur la page https://enthic-dataviz.netlify.app/entreprises/304668577
Mais se peut qu'il y ait d'autre entreprises avec d'autres manques dans les données, qui causent d'autres erreurs.

**Comment by QuentinMadura** [comment]
close

**Comment by QuentinMadura** [comment]
close
