### ISSUE TITLE
Automatiser la vérification de la qualité du code (naming, indentation, compléxité, etc...)

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#11]
Il faudrait utiliser GithubActions pour faire de la vérification automatique de la qualité de code (indentation, nom de variable, commentaires, etc...) sur les Pull Request, afin de valider la qualité d'une PR sur ce plan là.

**Comment by QuentinMadura** [comment]
Je pense qu'il y a deux PR séparées : 
- Une concernant les actions de GitHub à configurer 
- L'autre pour la configuration d'ESLint

**Comment by QuentinMadura** [comment]
close
