### ISSUE TITLE
Améliorer globalement les couleurs et la police du site.

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#14]
Pour l'instant, le site n'a pas vraiment bénéficié d'une réflexion sur les couleurs à utiliser, ni la police, la taille des titres, etc...
Si quelqu'un⋅e veut se lancer dessus, c'est possible :-)
On peut s'inspirer des couleurs déjà utilisées sur le site enthic.fr ou le logo ou le site actuel.
On peut aussi s'inspirer d'une palette crée pour l'occasion, ou bien d'un autre site qu'on aime bien, comme par exemple https://lafranceinsoumise.fr/

**Comment by QuentinMadura** [comment]
Je propose de démarrer par une homogénéisation des titres, des couleurs et de la police :)
