### ISSUE TITLE
Ajouter un bouton pour télécharger les données en csv

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#17]
Dans la page détail d'une entreprise, il faudrait ajouter un bouton permettant de télécharge un fichier csv contenant l'ensemble des données sous la forme : une ligne par année, une colonne par type de données.

**Comment by QuentinMadura** [comment]
Je me demande si ce n'est pas au back-end de faire ce travail ? Sachant que c'est beaucoup plus simple avec des outils comme Pandas de faire ce type de tâche :)

**Comment by leonarf** [comment]
Effectivement, j'ai ajouté une issue sur le repo du back-end : https://github.com/phe-sto/enthic/issues/23
