### ISSUE TITLE
Mettre la barre de recherche dans la page de résultat

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#5]
Sur la page de résultat de recherche (par exemple https://enthic-dataviz.netlify.app/recherche?text=enercoop) il faudrait pouvoir relancer la recherche, changer le texte de recherche, voir accéder aux filtres quand ils existeront.

**Comment by QuentinMadura** [comment]
Identiquement au commentaire sur l'issue https://github.com/CodeforFR/enthic-dataviz/issues/6, à terme, le plus simple serait de pouvoir manager globalement le "state" de la recherche dans l'application

**Comment by JulienRobberechts** [comment]
Pour cet issue il faut probablement juste insérer le composant <SearchBar /> dans la page Search.vue.
Un store permettrait de conserver des donnés mais si on a une solution simple sans, c'est pas plus mal. Faire simple c'est compliqué mais ça peut être une bonne stratégie. Bon mais si on a vraiment besoin d'un store, on le fait :-)
