### ISSUE TITLE
Search result bug on enercop

### ISSUE THREAD

**Issue by JulienRobberechts** [CodeforFR/enthic-dataviz#66]
Si je fais une faute à enercop le nombre résultat annoncé est bon mais il n'y a aucun résulats : 
http://localhost:8080/recherche?text=enercop

C'est un bug back-end

**Comment by JulienRobberechts** [comment]
Autre bug quand on tape correctement enercoop
http://localhost:8080/recherche?text=enercoop
on a totalItems = 1 au lieu de 11
et bien 11 résultats !

**Comment by leonarf** [comment]
Maintenant, https://enthic-dataviz.netlify.app/recherche?text=enercoop renvoi bien 11 résultats et https://enthic-dataviz.netlify.app/recherche?text=enercop zéro.
La modification apportée au back end est lisible sur https://github.com/phe-sto/enthic/commit/46c3eeaf336a76fc522bbd3cced972f0253c017e :
en fait, MariaDB ne renvoi pas le bon nombre sur la requête "COUNT" du coup j'ai implémenté un contournement pour vérifier la cohérence avec le numéro de page demandé, le nombre de résultat par page, et le nombre de résultat à la page demandée.
Je ne sais pas du tout quelle erreur dans la configuration de MariaDB est la source de l'erreur sur la requête COUNT.
