### ISSUE TITLE
Extraire les 2 graphiques de la vue detail en 1 ou 2 composants.

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#7]
Le fichier src/components/company/DynamicDetail.vue gère la page de présentation des données d'une entreprise.
Mais ce fichier est trop gros, et il faudrait extraire le code responsable de l'affichage des 2 graphiques de la page pour en faire un ou deux composants séparés.
Voir par exemple la page https://enthic-dataviz.netlify.app/entreprises/484223094 qui contient bien 2 graphiques :  Répartition du chiffre d'affaire  et  Répartition de la marge de l'entreprise

**Comment by QuentinMadura** [comment]
lien de la PR #28
