### ISSUE TITLE
Nettoyer le fichier src/components/company/DynamicDetail.vue

### ISSUE THREAD

**Issue by leonarf** [CodeforFR/enthic-dataviz#9]
Le fichier src/components/company/DynamicDetail.vue a été importé directement de l'ancienne version du projet, et le code n'a pas trop été retouché/amélioré/nettoyé. Il y a matière à l'amélioration.

**Comment by QuentinMadura** [comment]
lien de la PR #28

**Comment by leonarf** [comment]
Il reste notamment à supprimer le code qui affiche "see_website" et "see_contact" dans le bloc dont le titre est "Autres données présentes dans la base Enthic, mais pas valorisées ici : " sur la page détail (par exemple https://enthic-dataviz.netlify.app/entreprises/815282843).
